// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Robolink.Infrastructure.Data;

#nullable disable

namespace Robolink.Infrastructure.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Robolink.Core.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Industry")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasDefaultValue(new byte[0]);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("188cd869-567e-4cd2-870a-48bdb04af5cd"),
                            ContactEmail = "contact@samsung.com",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Industry = "Electronics",
                            IsDeleted = false,
                            Name = "Samsung Vina",
                            RowVersion = new byte[0]
                        });
                });

            modelBuilder.Entity("Robolink.Core.Entities.PhaseTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignedStaffId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<decimal?>("CustomerBudget")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EstimatedHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("InternalBudget")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ParentPhaseTaskId")
                        .HasColumnType("uuid");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<short>("ProcessRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectSystemPhaseConfigId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasDefaultValue(new byte[0]);

                    b.Property<Guid?>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignedStaffId");

                    b.HasIndex("ParentPhaseTaskId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectSystemPhaseConfigId");

                    b.HasIndex("StaffId");

                    b.ToTable("PhaseTasks");
                });

            modelBuilder.Entity("Robolink.Core.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CalculationConfigJson")
                        .HasColumnType("text");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContactPIC")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<decimal?>("CustomerBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("InternalBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("ProjectCode")
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasDefaultValue(new byte[0]);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("ParentProjectId");

                    b.HasIndex("ProjectCode")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Robolink.Core.Entities.ProjectSystemPhaseConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CustomDescription")
                        .HasColumnType("text");

                    b.Property<string>("CustomPhaseName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasDefaultValue(new byte[0]);

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<Guid>("SystemPhaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SystemPhaseId");

                    b.HasIndex("ProjectId", "SystemPhaseId")
                        .IsUnique();

                    b.ToTable("ProjectSystemPhaseConfigs");
                });

            modelBuilder.Entity("Robolink.Core.Entities.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("Department")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasDefaultValue(new byte[0]);

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Staffs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1b8c3dbf-63bb-4207-b108-9b28706185a7"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = 1,
                            FullName = "Huy Dang",
                            IsDeleted = false,
                            PasswordHash = "AQAAAAEAACcQAAAAE...",
                            Role = 1,
                            RowVersion = new byte[0],
                            Status = 0,
                            Username = "huydang.admin"
                        });
                });

            modelBuilder.Entity("Robolink.Core.Entities.SystemPhase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("DefaultSequence")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasDefaultValue(new byte[0]);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SystemPhases");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 30, 2, 38, 38, 0, DateTimeKind.Utc),
                            DefaultSequence = 1,
                            Description = "Project initialization and setup",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Initialize",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 1, 30, 2, 38, 38, 0, DateTimeKind.Utc),
                            DefaultSequence = 2,
                            Description = "Design and engineering phase",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Engineering",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 1, 30, 2, 38, 38, 0, DateTimeKind.Utc),
                            DefaultSequence = 3,
                            Description = "Manufacturing and fabrication",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Fabrication",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 1, 30, 2, 38, 38, 0, DateTimeKind.Utc),
                            DefaultSequence = 4,
                            Description = "CNC cutting operations",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "CNC Cutting",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 1, 30, 2, 38, 38, 0, DateTimeKind.Utc),
                            DefaultSequence = 5,
                            Description = "Product assembly phase",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Assembly",
                            RowVersion = new byte[0]
                        });
                });

            modelBuilder.Entity("Robolink.Core.Entities.WorkLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DynamicDataJson")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PhaseTaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasDefaultValue(new byte[0]);

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<decimal?>("V1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("V10")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("V2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("V3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("V4")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("V5")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("V6")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("V7")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("V8")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("V9")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValueMain")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValueSub")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.HasIndex("PhaseTaskId");

                    b.HasIndex("ProjectId");

                    b.ToTable("WorkLogs");
                });

            modelBuilder.Entity("Robolink.Core.Entities.PhaseTask", b =>
                {
                    b.HasOne("Robolink.Core.Entities.Staff", "AssignedStaff")
                        .WithMany()
                        .HasForeignKey("AssignedStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Robolink.Core.Entities.PhaseTask", "ParentPhaseTask")
                        .WithMany("SubPhaseTasksItems")
                        .HasForeignKey("ParentPhaseTaskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Robolink.Core.Entities.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Robolink.Core.Entities.ProjectSystemPhaseConfig", "PhaseConfig")
                        .WithMany("PhaseTasks")
                        .HasForeignKey("ProjectSystemPhaseConfigId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Robolink.Core.Entities.Staff", null)
                        .WithMany("AssignedTasks")
                        .HasForeignKey("StaffId");

                    b.Navigation("AssignedStaff");

                    b.Navigation("ParentPhaseTask");

                    b.Navigation("PhaseConfig");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Robolink.Core.Entities.Project", b =>
                {
                    b.HasOne("Robolink.Core.Entities.Client", "Client")
                        .WithMany("Projects")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Robolink.Core.Entities.Staff", "Manager")
                        .WithMany("ManagedProjects")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Robolink.Core.Entities.Project", "ParentProject")
                        .WithMany("SubProjectsItems")
                        .HasForeignKey("ParentProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Client");

                    b.Navigation("Manager");

                    b.Navigation("ParentProject");
                });

            modelBuilder.Entity("Robolink.Core.Entities.ProjectSystemPhaseConfig", b =>
                {
                    b.HasOne("Robolink.Core.Entities.Project", "Project")
                        .WithMany("PhaseConfigs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Robolink.Core.Entities.SystemPhase", "SystemPhase")
                        .WithMany("ProjectConfigs")
                        .HasForeignKey("SystemPhaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("SystemPhase");
                });

            modelBuilder.Entity("Robolink.Core.Entities.WorkLog", b =>
                {
                    b.HasOne("Robolink.Core.Entities.Staff", "Operator")
                        .WithMany("WorkLogs")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Robolink.Core.Entities.PhaseTask", "WorkTask")
                        .WithMany("WorkLogs")
                        .HasForeignKey("PhaseTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Robolink.Core.Entities.Project", "WorkProject")
                        .WithMany("WorkLogs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Operator");

                    b.Navigation("WorkProject");

                    b.Navigation("WorkTask");
                });

            modelBuilder.Entity("Robolink.Core.Entities.Client", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Robolink.Core.Entities.PhaseTask", b =>
                {
                    b.Navigation("SubPhaseTasksItems");

                    b.Navigation("WorkLogs");
                });

            modelBuilder.Entity("Robolink.Core.Entities.Project", b =>
                {
                    b.Navigation("PhaseConfigs");

                    b.Navigation("SubProjectsItems");

                    b.Navigation("Tasks");

                    b.Navigation("WorkLogs");
                });

            modelBuilder.Entity("Robolink.Core.Entities.ProjectSystemPhaseConfig", b =>
                {
                    b.Navigation("PhaseTasks");
                });

            modelBuilder.Entity("Robolink.Core.Entities.Staff", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("ManagedProjects");

                    b.Navigation("WorkLogs");
                });

            modelBuilder.Entity("Robolink.Core.Entities.SystemPhase", b =>
                {
                    b.Navigation("ProjectConfigs");
                });
#pragma warning restore 612, 618
        }
    }
}
